### ISSUE TITLE
客户端怎么使用呢？

### ISSUE THREAD

**Issue by zhulin0001** [yuanfengyun/chess_server#1]
感谢分享的代码，我已经成功把server部署起来了。在使用代码中test/client.lua时，不知道怎么进行send操作，还请解答一下，谢谢！

**Comment by yuanfengyun** [comment]
进入skynet目录， ./3rd/lua/lua examples/client.lua

**Comment by zhulin0001** [comment]
Sorry，我没表达清楚，我是说，server部署起来之后，我用skynet运行了client.lua，输入help看到有send操作，但是我不清楚具体要怎么填写参数才能进一步测试server代码

**Comment by yuanfengyun** [comment]
客户端用chess项目
